services:
  bobo:
    image: thisguygil/bobo:latest
    container_name: bobo
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - bobonet

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - bobonet

volumes:
  mysql-data:

networks:
  bobonet:
    name: bobonet